server:
  port: 9999

spring:
  banner:
    location: classpath:banner.txt

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml